name: publish
on: [push]
jobs:
publish-hello-docker-image:
runs-on: ubuntu-latest
steps:
- uses: actions/checkout@v2
- name: Login to GitHub Container Registry
uses: docker/login-action@v1
with:
registry: github.com
username: ${{ github.actor }}
password: ${{ secrets.GITHUB_TOKEN }}
- name: Build the python-3.9.16-slim-buster-gdal Docker image
run: |
       docker build . --tag github.com/bfeist/python-3.9.16-slim-buster-gdal:latest
       docker run github.com/bfeist/python-3.9.16-slim-buster-gdal:latest
       docker push github.com/bfeist/python-3.9.16-slim-buster-gdal:latest